.gitignore
TensorToolbox/tensor.py

in the tensor class we have issues when using reshape as it does not match MATLAB TensorToolbox, not sure how far this propagates, but here is one fix that I need to do to match Matlab

fix reshape to match matlab

---

pyttb/tensor.py
tests/test_tensor.py

Fixing np.reshape usage. Adding more tests for tensor.ttv.

---

pyttb/ktensor.py
pyttb/pyttb_utils.py
pyttb/sptensor.py
pyttb/tensor.py
tests/test_ktensor.py
tests/test_pyttb_utils.py
tests/test_sptensor.py
tests/test_tensor.py

Implement ktensor.score and associated tests.

---

pyttb/ktensor.py
pyttb/sptensor.py
pyttb/tensor.py
tests/test_ktensor.py
tests/test_sptensor.py
tests/test_tensor.py

Resolve some issues involving deprecations and changes in NumPy 1.24.
- Type aliases ``numpy.float`` and ``numpy.int`` were deprecated in 1.20 and removed in 1.24, so replace with built-ins ``float`` and ``int``. These are identical replacements: https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
- Creating ragged numpy arrays (numpy calls them inhomogeneous) is no longer allowed. To get an ordered set of numpy arrays with different dimensions (e.g. the ``vector`` argument of the ``ttv`` methods) allow plain lists to be used. This is a backward-compatible change - as long as you can construct ``vector`` as a numpy.ndarray, you can still pass it.
For an example of the second issue, in numpy 1.24:
```
>>> import numpy as np …
```

Compatibility with numpy 1.24.x

---

pyttb/tensor.py
tests/test_tensor.py

A proposed fix to: https://github.com/sandialabs/pyttb/issues/41
For general tensors we should be able to defer to numpy slicing mechanics as the easiest solution. There is some ambiguity when slicing across multiple dimensions when it comes to retaining or dropping singleton dimensions. I don't have MATLAB access so I am not sure how it is handled there. All of our tests still pass and we never specifically enforced this so it might not be an issue.
Example:
```
import numpy
tensor = np.ones((3,3,3,3))
sliced = tensor[:, 0, :, 0]
sliced.shape # in numpy this is a matrix so shape is (3,3) but one could argue (1, 3, 1, 3) is possibly useful/valid
```
This came up when validating TTENSOR implementation so is a pre-requisite for that PR.

TENSOR: Fix slices ref when return value isn't scalar or vector. #41

---

pyttb/sptensor.py
pyttb/tensor.py
pyttb/ttensor.py
tests/test_sptensor.py
tests/test_tensor.py
tests/test_ttensor.py

Preliminary solution to https://github.com/sandialabs/pyttb/issues/10
The first commit here is [this ](https://github.com/sandialabs/pyttb/pull/50) which I used to test ttensor for consistency [here](https://github.com/ntjohnson1/pyttb/blob/3ac89ea59620b9792830f7ad9d17ba8e819c92e8/tests/test_ttensor.py#L285-L286) if that proves a problem could probably validate a different way or take this with less coverage and follow up.
Limitations:
- Dense core only
- Extending to other cores shouldn't be difficult but it might be nice to abstract our the required core interface so we can filter on that instead of the list of methods that are needed. In theory could rely on runtime details instead.

Ttensor implementation

---

pyttb/cp_apr.py
pyttb/sptensor.py
pyttb/tenmat.py
pyttb/tensor.py
tests/test_cp_apr.py
tests/test_packaging.py
tests/test_pyttb_utils.py
tests/test_sptensor.py
tests/test_tensor.py

Improvements towards https://github.com/sandialabs/pyttb/issues/14 doesn't get to 100% but cuts uncovered lines by about half.
NOTE: The first commit (to avoid a mess) is included in https://github.com/sandialabs/pyttb/pull/51 but the two PRs aren't mutually exclusive. It's fine to go in with either since I think it is justified in isolation.
Before:
```
Name                   Stmts   Miss  Cover   Missing
----------------------------------------------------
pyttb\__init__.py         23      1    96%   31
pyttb\cp_als.py           87      0   100%
pyttb\cp_apr.py          567     78    86%   84, 86, 88, 110, 197-198, 229, 247-249, 342, 351, 374-384, 419-432, 46
4-469, 495, 536, 540-541, 649, 658, 681-691, 719-732, 781-786, 808, 813, 819, 871-872, 1016, 1034-1037, 1044-1045,
1230, …
```

Test coverage

---

.github/workflows/regression-tests.yml
conftest.py
pyproject.toml
pytest.ini
pyttb/cp_als.py
pyttb/khatrirao.py
pyttb/ktensor.py
pyttb/pyttb_utils.py
pyttb/sptensor.py
pyttb/tensor.py
pyttb/ttensor.py
setup.py
tests/test_package.py
tests/test_tensor.py

This is partially in response to https://github.com/sandialabs/pyttb/issues/20 but is also a proposal/RFC. Depending on opinions can figure out how to break out the pieces of the proposal into separate PRs/issues.
Parts to the proposal:
1. Add autoformatting via black and isort
- This can be applied automatically across pyttb
- This should be fast to enforce
1. Add linting checks via pylint
- This will require either adding the checking and excusing all existing failures or manually applying this file by file
- This is slow to enforce on the scope of current tests (a few seconds)
1. Add static type checking via mypy
- We can opt in the whole pyttb right now since there are no types anywhere. Then enforce it as we transition to types
- This isn't particularly slow to enforce
1. Enforce …

Tensor docs plus Linting and Typing and Black oh my

---

pyttb/pyttb_utils.py
pyttb/ttensor.py
pyttb/tucker_als.py
tests/test_ttensor.py
tests/test_tucker_als.py

* Replace usage in tucker_als
* Update test for tucker_als to ensure result matches expectation
* Add early error handling in ttensor ttm for negative dims

TUCKER_ALS: TTM with negative values is broken in ttensor (#62)

---

pyttb/pyttb_utils.py
pyttb/sptensor.py
pyttb/tensor.py
tests/test_package.py
tests/test_pyttb_utils.py
tests/test_sptensor.py

Related to https://github.com/sandialabs/pyttb/issues/63
The commits mostly break down the work but this covers pyttb_utils and sptensor for pylint, but just sptensor for typing. I think will need the tensor implementations to be typed for the utils that act on tensors to place nice with types.
Continuing to add typing across the base classes. The native python numeric types vs numpy numeric types isn't generally resolved yet. I think the typing is helping to see all the places we use it but I probably need to make an issue to track this globally. I've moved towards `isinstance(variable, (int,float,np.generic))` to basically catch numpy scalars but I'd need to dig around a bit more to see if there is a standard for switching back and forth while also playing nicely with typing.
I …

Lint pyttb_utils and lint/type sptensor

---

pyttb/ktensor.py
pyttb/pyttb_utils.py
pyttb/sptensor.py
pyttb/tensor.py
pyttb/ttensor.py
pyttb/tucker_als.py
tests/test_ktensor.py
tests/test_pyttb_utils.py
tests/test_sptensor.py
tests/test_tensor.py
tests/test_ttensor.py

This should be the general solution to this unless I missed something https://github.com/sandialabs/pyttb/issues/62
I moved from:
`tt_dimscheck(dims: np.ndarray, N: int, M: None = None)`
to:
`tt_dimscheck(N: int, M: None = None, dims: Optional[np.ndarray] = None, exclude_dims: Optional[np.ndarray] = None)`
If anyone really relied on our interface that is a breaking change, but the right one in my opinion. Since user base is small PROBABLY ok to just do 1.6.0 (since this util is mostly used internally). This interface change then worked its way out to <tensor,ttensor,ktensor,sptensor>.<ttv,ttm> which were also breaking changes but more minor. We could do this more gently if worried about compatibility.
Notes:
* For tensor.ttsv I changed the name entirely since the use of dim is quite …

Exclude dims

---

docs/source/algorithms.rst
docs/source/conf.py
docs/source/hosvd.rst
docs/source/sptensor.rst
docs/source/tensor_classes.rst
docs/source/ttensor.rst
docs/source/tuckerals.rst

Should resolve: #97
We could consider a github action to preview the docs but that's probably not high priority. Will try to remember to add this for new code. For most of it the autogeneration will pickup new code added in configured files.

Link in autodocumentation for recently added code

---

pyttb/ktensor.py
pyttb/sptensor.py
pyttb/tensor.py
pyttb/ttensor.py
tests/test_cp_als.py
tests/test_ktensor.py
tests/test_sptensor.py
tests/test_tensor.py
tests/test_ttensor.py

I think an enhancement that probably isn't blocking for 2.0 is considering a more standard logging control. Some algorithms take log levels that aren't consistent with each other and use prints. I've been move more things over to `logging` we can probably add a `pyttb` level logging control rather than the root logger for a file. This allows a more standard way to control verbosity.
All of that to say for now I moved the warning to a debug level log, because I think we added the warning initially in case someone hit some weird numeric behavior with the cast (I don't remember entirely).

Remove warning for nvecs:

---

pyttb/sptensor.py
pyttb/tensor.py
tests/test_sptensor.py
tests/test_tensor.py

This PR is to tackle the original issue as described here https://github.com/sandialabs/pyttb/issues/92 where certain access patterns weren't growing our tensor when using setitem. I've opened https://github.com/sandialabs/pyttb/issues/108 to follow up for some lack of intuitiveness/consistency on our general indexing scheme and how it deviates from the MATLAB implementation.
This is probably easiest to review commit by commit because two of the commits move a lot of code to break out our indexing into isolated sub-components for easier readability/debugability. The new tests should highlight behaviors that weren't supported prior to this change.

Tensor growth

---

pyttb/sptensor.py
pyttb/tensor.py
tests/test_sptensor.py
tests/test_tensor.py

There is definitely cleanup that could be done around our indexing tests and potentially the logic. There are a lot of different paths through the code based on a variety of conditions that makes it complicated to reason about.
This proposes a solution to: https://github.com/sandialabs/pyttb/issues/108
Here are all the different combinations that I could think of and expected behavior based on Danny's description in the linked issue/discussion. I basically used this as my burn down list to confirm consistency. If there are disagreements here I think the small examples help for concreteness (and I baked some into our unit tests). The fundamental problem was the sub-scripts had different meanings in pyttb between sptensor and tensor. Ultimately, that made me question how everything …

Tensor indexing

---

pyttb/cp_apr.py
pyttb/khatrirao.py
pyttb/ktensor.py
pyttb/sptensor.py
pyttb/tensor.py
tests/test_khatrirao.py
tests/test_package.py

I was looking at our khatrirao implementation and realized it needed a little TLC. This is a small PR:
1. Remove debug prints (could leave them in place a logs at a debug level so they can be turned back on in the future but I assume for now can just prune)
2. Update interface to only take repeated matrices to simplify
3. Add linting and typing to improve our coverage and also to validate everything matches the new interface. Since a lot of our core tensors already have types this immediately pointed out incorrect usages just based on types.
4. We had special cased things based on the value of ncols_first but that doesn't actually look like it is required

Khatrirao cleanup

---

pyttb/hosvd.py
pyttb/khatrirao.py
pyttb/ktensor.py
pyttb/pyttb_utils.py
pyttb/sptenmat.py
pyttb/sptensor.py
pyttb/sptensor3.py
pyttb/sumtensor.py
pyttb/symktensor.py
pyttb/symtensor.py
pyttb/tensor.py
pyttb/tucker_als.py
tests/test_hosvd.py
tests/test_package.py
tests/test_sptenmat.py
tests/test_sptensor3.py
tests/test_sumtensor.py
tests/test_symktensor.py
tests/test_symtensor.py

Fixing minor issues: all classes inheriting from object, copyright notice, more complete testing, removing random docstrings

Class inheritance and docstrings

---

.github/workflows/regression-tests.yml

Following the coveralls python package suggestion here seems to resolve our issues with weird coverage in our github action. https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
NOTE: Do we use the sphinx_rtd_theme anywhere for our current testing/deployment? I don't think so. If we do we should probably update our automation to `pip install .[dev,doc]` instead of manually specifiying the theme (manually specifying coveralls since that is only for the action makes sense still). But that's more energy than I have for this tonight.

Coveralls: Try updating to default suggestion

---

docs/source/index.rst
pyttb/sptensor.py

This is simpler solution to the confusion here https://github.com/sandialabs/pyttb/issues/113 basically from_data does no validation but that is not explicit in the doc string so add the clarification. More broadly I know you discussed trying to unify our constructors so the user doesn't necessarily need to think about it. It is a little verbose that the `standard` way to construct with validation is `from_aggregator`.
Also while I was checking the generated doc I saw the warning that we've never actually linked in our bibtex
doc. We can probably provide a nicer sentence/cleanup but I figured it would be good to at least generate the set of references to original algorithms on our read the docs. It might be worth getting a fresh set of eyes from @DeepBlockDeepak on the read the docs to …

Sptensor clarification

---

.gitignore
pyttb/cp_als.py
pyttb/cp_apr.py
pyttb/import_data.py
pyttb/ktensor.py
pyttb/tensor.py
tests/test_cp_apr.py
tests/test_import_export_data.py
tests/test_ktensor.py
tests/test_sptensor.py
tests/test_tensor.py
tests/test_ttensor.py

Addresses the `ktensor` part of:
- #145 
- 
----
:books: Documentation preview :books:: https://pyttb--182.org.readthedocs.build/en/182/

145 add support for constructing from data without copying (ktensor)

---

.readthedocs.yaml
docs/source/conf.py
docs/source/tutorial/CP_APR.ipynb
pyproject.toml
pyttb/__init__.py
pyttb/pyttb_utils.py
pyttb/tenmat.py
pyttb/tensor.py
pyttb/ttensor.py
tests/test_package.py
tests/test_tenmat.py
tests/test_ttensor.py

This covers linting and typing for TTENSOR, TENMAT, and PYTTB_UTILS.
For users of the data structures as a toolbox this should be sufficient typing coverage to be interesting/useful. So additionally I added [py.typed](https://peps.python.org/pep-0561/) to the package so next release it will be incorporated in the wheel. With the ktensor changes next release probably needs to be 1.7 anyway.
I updated the ticket to cover the [algorithms](https://github.com/sandialabs/pyttb/issues/63) next. There are definitely quality of life improvements around centralizing some common logic and types to make consistency easier. But IMO the primary value is getting initial coverage everywhere so the lay of the land is a bit clearer.
----
:books: Documentation preview :books:: …

Finish Core Typing

---

pyttb/__init__.py
pyttb/cp_als.py
pyttb/cp_apr.py
pyttb/export_data.py
pyttb/hosvd.py
pyttb/import_data.py
pyttb/khatrirao.py
pyttb/ktensor.py
pyttb/pyttb_utils.py
pyttb/sptenmat.py
pyttb/sptensor.py
pyttb/sptensor3.py
pyttb/sumtensor.py
pyttb/symktensor.py
pyttb/symtensor.py
pyttb/tenmat.py
pyttb/tensor.py
pyttb/ttensor.py
pyttb/tucker_als.py
tests/test_cp_apr.py
tests/test_package.py

Resolves: https://github.com/sandialabs/pyttb/issues/63
* Adds typing and linting to the remaining components of pyttb.
* Fixes a formatting error in our docstrings I introduced. Now all our parameters shouldn't have a hard coded type and display properly. Our type hints provide types to documentation.
* Always follow up improvements possible for our typing. General direction of allowing the most general input and the most specific output. But at least we have pinned what we currently support. Adding some helper type definitions to unify the look/feel of our interfaces is probably a good next step but probably not critical path for 2.0.
* Lots of mostly non-functional changes. Might be easier to review by commit where I explained what typing/linting changes I addressed.
----
:books: …

Finish Typing/Linting Pyttb Initial Support

---

pyttb/cp_als.py
pyttb/ktensor.py
pyttb/sptensor.py
pyttb/tenmat.py
pyttb/tensor.py
tests/test_import_export_data.py
tests/test_khatrirao.py
tests/test_ktensor.py
tests/test_pyttb_utils.py
tests/test_sptensor.py
tests/test_tenmat.py
tests/test_tensor.py

Catching a few odds and ends:
* https://github.com/sandialabs/pyttb/issues/185
* https://github.com/sandialabs/pyttb/issues/183
* https://github.com/sandialabs/pyttb/issues/179
One commit each. The (array==array).all() pattern caught a few minor bugs but nothing substantial.
----
:books: Documentation preview :books:: https://pyttb--195.org.readthedocs.build/en/195/

End & array_equal & shape

---

docs/source/conf.py
pyproject.toml

* Our types linked to 3.6, make 3.8
* collapse displayed wrong, this fixes it by not evaluating default values (updated our minimum sphinx to 4.0 to support the setting)
See our [latest ](https://pyttb.readthedocs.io/en/latest/sptensor.html#pyttb.sptensor.sptensor.collapse)for collapse vs the updated [preview ](https://pyttb--196.org.readthedocs.build/en/196/sptensor.html#pyttb.sptensor.sptensor.collapse) as far as I can tell this evaluates `np.sum` which is the function handle and fails to display properly. By just using the literal value things seem to be ok and not break elsewhere. If this ends up causing additional issues we may need to just default to None values and set the default internally.
----
:books: Documentation preview :books:: …

Documentation minor format fixes

---

pyttb/gcp/samplers.py
tests/gcp/test_samplers.py

Sampler support for gcp_opt. Related to but doesn't complete https://github.com/sandialabs/pyttb/issues/58.
The tests are probably a little light but I don't have any clever ideas at the moment on how to better validate them. I cover the major portions but for example uniform could be sampling with a totally different distribution and still pass.
I updated my previous comment here, and dropped common commits so this is now distinct from https://github.com/sandialabs/pyttb/pull/200. Merge order shouldn't matter.
----
:books: Documentation preview :books:: https://pyttb--201.org.readthedocs.build/en/201/

Gcp samplers

---

.github/workflows/regression-tests.yml
.pre-commit-config.yaml
CONTRIBUTING.md
pyproject.toml
pytest.ini
pyttb/cp_als.py
pyttb/cp_apr.py
pyttb/export_data.py
pyttb/gcp/fg_est.py
pyttb/gcp/fg_setup.py
pyttb/gcp/optimizers.py
pyttb/gcp/samplers.py
pyttb/gcp_opt.py
pyttb/hosvd.py
pyttb/import_data.py
pyttb/ktensor.py
pyttb/pyttb_utils.py
pyttb/sptenmat.py
pyttb/sptensor.py
pyttb/sptensor3.py
pyttb/sumtensor.py
pyttb/symktensor.py
pyttb/symtensor.py
pyttb/tenmat.py
pyttb/tensor.py
pyttb/ttensor.py
pyttb/tucker_als.py
tests/test_package.py

Follow up to: https://github.com/sandialabs/pyttb/pull/211
Remove isort and pylint from the repo after the addition of ruff:
* Remove packaging from dev deps
* Remove tests that run them (ci and pytest)
* Remove packaging pytest marker now that things run fast by default
* Add python 3.11 to test combinations
* Remove all the pylint disabled lines

Remove isort pylint

---

pyttb/sptensor.py
tests/test_sptensor.py

Should resolve #215 we made things column vectors in sptensor to match MATLAB. We may want to consider just making them flat 1-D vectors in the future to simplify, OR something I haven't written up anywhere is that tensorly uses [this](https://sparse.pydata.org/en/stable/) sparse package for their numpy backend. Might be worth investigating post 2.0.
In the meantime this resolves and I updated our test to enforce this stays resolved. Similar to my previous note where I moved lots of things to np.array_equal continuing to rely on that is probably useful to resolve scalar vs single element in arrays of various inflated shapes.
----
:books: Documentation preview :books:: https://pyttb--217.org.readthedocs.build/en/217/

Sptensor innerprod float

---

docs/source/ktensor.rst
docs/source/sptensor.rst
docs/source/tenmat.rst
docs/source/tensor.rst
docs/source/ttensor.rst
pyttb/ktensor.py
pyttb/sptensor.py
pyttb/tensor.py
tests/test_tensor.py

Pulling in other doc updates.
----
:books: Documentation preview :books:: https://pyttb--218.org.readthedocs.build/en/218/

20 tensor complete documentation for all methods

---

docs/source/tutorial/class_ktensor.ipynb
pyttb/cp_apr.py
pyttb/ktensor.py
pyttb/sptensor.py
pyttb/ttensor.py
tests/test_cp_apr.py
tests/test_ktensor.py

Resolves: https://github.com/sandialabs/pyttb/issues/165 by removing getitem and setitem from ktensor. The interpretation for ktensor is different than tensor and sptensor. This brings ktensor closer in line with ttensor and reduces the surface we have to cover.
Resolves: https://github.com/sandialabs/pyttb/issues/168 by incorporating the index changes above and the note from https://github.com/sandialabs/pyttb/issues/167
----
:books: Documentation preview :books:: https://pyttb--220.org.readthedocs.build/en/220/

Ktensor tutorial cleanup

---

pyttb/__init__.py
pyttb/tensor.py
tests/test_tensor.py

I found myself in a loud coffee shop unable to work on other stuff so I picked off #72. I am not sure if the custom combinator code is needed elsewhere but itertools combinations with replacement should be an appropriate replacement with the advantage that it doesn't have to actually generate all the index sets in memory. On my laptop I didn't see any major improvement for this because N>=8, M>=8 had a huge result tensor anyway.
----
:books: Documentation preview :books:: https://pyttb--222.org.readthedocs.build/en/222/

Teneye: Add preliminary implementation and tests

---

pyttb/sptensor.py
tests/test_sptensor.py

Quick fix to https://github.com/sandialabs/pyttb/issues/232 to unblock the documentation effort for sptensor.
Probably not critical prior to 2.0 but we might consider a refactor of the constructor internals at some point. Originally (matching MATLAB) we had from_data which basically put all error handling onto the user for the benefit of speed. Then we had from_aggregator which has a lot more error checking but was the recommended approach. Now we moved from_data to our __init__ but are slowly adding in lots of error checking. We might be able to merge from_aggregator into our __init__ then have an optimized happy path with minimal checks then a slower path that covers more edge cases.
----
:books: Documentation preview :books:: https://pyttb--243.org.readthedocs.build/en/243/

SPTENSOR: Infer shape from data

---

pyttb/gcp/optimizers.py
pyttb/sptensor.py
tests/test_sptensor.py

This should resolve #251 and #252. Testing for logging is a little brittle/would require some more thought. I think the tutorials should serve to capture whatever formatting issue I had before with the inf check. I think these are mostly helpful to unblock the tutorial and if people felt strongly could file an issue to follow up with better testing.
----
:books: Documentation preview :books:: https://pyttb--255.org.readthedocs.build/en/255/

Gcp opt tutorial fixes

---

pyttb/pyttb_utils.py
pyttb/sptensor.py
tests/test_pyttb_utils.py
tests/test_sptensor.py

We were using `tt_ismember_rows` incorrectly in mask. `-1` was a flag for failed match but also yields a valid index into an array. First fixed the bug then updated the ismember_rows interface to try to make this incorrect usage more obvious in the future.
Resolves https://github.com/sandialabs/pyttb/issues/258
----
:books: Documentation preview :books:: https://pyttb--259.org.readthedocs.build/en/259/

Sptensor mask

---

pyttb/sptensor.py
pyttb/tensor.py
tests/test_sptensor.py
tests/test_tensor.py

Resolves #256 and #257 but maybe raises more questions than it answers. It matches what you described as expected behavior. (Indicator tensors with 1.0, 0.0)
It raises the question on if we should track the dtype (could be a hidden variable or a property). Or even more explicitly could be set when constructing the tensor (I kind of hacked the vals in the sptensor to make things make sense; however would be nice to take a dtype argument on construction).
You mentioned in the issue we don't do boolean tensors but for equality we currently do. Should those also get the same indicator treatment?
```python
>> import pyttb as ttb
>> T = ttb.tenones((2,2))
>> T == T
tensor of shape (2, 2)
data[:, :] =
[[ True  True]
[ True  True]]
```
----
:books: Documentation preview :books:: …

Sparse logical

---

docs/source/sptenmat.rst
docs/source/tensor_classes.rst
docs/source/tutorial/class_sptenmat.ipynb
pyttb/sptenmat.py
pyttb/sptensor.py
pyttb/tenmat.py
pyttb/ttensor.py
tests/test_sptenmat.py
tests/test_sptensor.py

This resolves #102 however the docstrings need updating and the constructors are still the old style. I think punting that to #214 to update sptenmat and tensmat to be consistent makes sense. I think I covered everything except for aatx since that doesn't seem to currently be used in the matlab version.
This continued to add tech debt around our tests being somewhat redundant (all the checks of the different components of sptenmat), but that's not priority before 2.0. At some point might be nice to revisit cleaning up our tests.
----
:books: Documentation preview :books:: https://pyttb--290.org.readthedocs.build/en/290/

Add sptenmat

---

pyttb/cp_als.py

An argument called `optdims` of type `List[int]` is added to `cp_als()` to enable optimizing only the factor matrices of specific modes.
This was not previously possible even by scripting around `cp_als()` since it checks for convergence only after each full sweep.
Control flow was hardly altered (`dimorder` may now just be missing some entries), and the default is of course optimizing all modes.
----
📚 Documentation preview 📚: https://pyttb--302.org.readthedocs.build/en/302/

Optimize only specific modes in cp_als()

---

pyttb/ktensor.py

Implements the more optimized version of `ktensor.full()` from MATLAB Tensor Toolbox. This results in an effective peak memory of `tensor_size` (down from `rank*tensor_size`) and a speedup of 5-50x depending on tensor shape and size.
See #299 for a more detailed discussion with benchmarks.
----
📚 Documentation preview 📚: https://pyttb--300.org.readthedocs.build/en/300/

Improve ktensor.full()

---

.github/workflows/markdown-check.yml
CITATION.bib
CONTRIBUTING.md
README.md

Update/simplify README, copyright, etc.
----
📚 Documentation preview 📚: https://pyttb--324.org.readthedocs.build/en/324/

110 need getting started documentation for users

---

.readthedocs.yaml
pyproject.toml
pyttb/ktensor.py
pyttb/sptenmat.py
pyttb/sptensor.py
pyttb/tenmat.py

Unpin numpy fixes #325 
* Update pretty print for sptenmat and tenmat
* Minor other formatting fixes in doc tests
Also updates our ktensor vis:
* Makes the returns match subplots so users can manipulate figure and axes in down stream usage
* Use the updated interface to automatically generate the opened figures in doctests (for me locally the doctest hang until the figures are closed)
I think this also finished removing 3.8 support.
----
📚 Documentation preview 📚: https://pyttb--329.org.readthedocs.build/en/329/

Unpin numpy

---

docs/source/tutorial/class_sptenmat.ipynb
docs/source/tutorials.rst

We can manage our tutorials on a single page with nice toc entries without too much additional work.
This fixes most of our existing things and provides the example for adding more pieces moving forwards.
One gotcha I had to fix here is that the `Desired TOC Entry`<notebook_path> format only works if there is a single top level header in the notebook. `#` if there are multiple the substitution fails.
I hadn't see the hierarchy in the matlab docs via `doc tensor_toolbox` prior to this issue.
Fixes #342 
I was editing while CI ran so the nice link didn't post [here](https://pyttb--343.org.readthedocs.build/en/343/) are the docs from this PR.

Fix our tutorial hierarchy

---

pyttb/cp_als.py
pyttb/cp_apr.py
pyttb/gcp/fg_est.py
pyttb/gcp/samplers.py
pyttb/hosvd.py
pyttb/ktensor.py
pyttb/pyttb_utils.py
pyttb/sptenmat.py
pyttb/sptensor.py
pyttb/sumtensor.py
pyttb/tenmat.py
pyttb/tensor.py
pyttb/ttensor.py
tests/test_ktensor.py
tests/test_tenmat.py
tests/test_tensor.py

Fixes #338 and also makes progress towards being more explicit/consistent about our Fortran formatting discussed [here](https://github.com/sandialabs/pyttb/discussions/344) and [here](https://github.com/sandialabs/pyttb/discussions/345#discussioncomment-11261517)
We probably want to capture the fortran ordering in our documentation somewhere and I should probably open an issue to make the ordering flow throughout pyttb so we can eventually support "C" ordering as well.
----
📚 Documentation preview 📚: https://pyttb--354.org.readthedocs.build/en/354/

Explicit layout and fix dense tensor printing

---

pyttb/tenmat.py

----
📚 Documentation preview 📚: https://pyttb--385.org.readthedocs.build/en/385/

Using matmul instead of @ to enforce order on tenmat product

---

tests/test_package.py

This should fix problems with spaces in the path names for  `{root_dir}` and `{toml_file}`.
I have spaces in my path names (on Windows) so that quotes are needed around `{root_dir}` and `{toml_file}` in the subprocess calls. I tried to make it so that these were escaped double quotes, and this worked fine. However, ruff insisted that I change the outer double quotes to single quotes and the inner escaped doubles quotes to regular double quotes. So that is what you're seeing in the pull request.
----
📚 Documentation preview 📚: https://pyttb--388.org.readthedocs.build/en/388/

Quotes needed for paths with spaces

---

docs/source/sptensor.rst
docs/source/tensor.rst

Documentation was missing related functions that are defined in the same file as the tensor and sptensor classes. These don't appear anywhere in the Python API documentation. Fixes #398.
----
📚 Documentation preview 📚: https://pyttb--399.org.readthedocs.build/en/399/

Fixing missing functions in documentation

---

docs/source/conf.py
pyttb/tensor.py

This change makes it so that you can see the functions inside each class from the navigation bar in the HTML documentation:
Fixes #400
----
📚 Documentation preview 📚: https://pyttb--401.org.readthedocs.build/en/401/

Fixing depth of HTML documentation

---

docs/source/cpals.rst
docs/source/cpapr.rst
docs/source/gcpopt.rst
docs/source/hosvd.rst
docs/source/ktensor.rst
docs/source/sptenmat.rst
docs/source/sptensor.rst
docs/source/sumtensor.rst
docs/source/tenmat.rst
docs/source/tensor.rst
docs/source/ttensor.rst
docs/source/tuckerals.rst

Fixing automodule versus autoclass or autofunction for classes and functions that are promoted to the pyttb level. Also adding notes to explain the promotion which is otherwise hidden from the user.
This mostly addresses #417 as well. I should have made #418 a subissue!
----
📚 Documentation preview 📚: https://pyttb--421.org.readthedocs.build/en/421/

Fixing #418 - Resolving namespace issues in documentation.

---

docs/source/tensor.rst
pyttb/tensor.py

- Move assumed module imports into `tensor.rst` so that it appears at the top of the document.
- Remove "TENSOR" in the class description, which is a remnant from MATLAB.
- Document the attributes of the class, which before were only partly documented.
- Document all the ways that a tensor can be created.
_Note:_ This does not depend on the other PRs. There may be some minor issue with `tensor.rst` depending on the order of the merges. If there is, let me know and I can fix.  There may be possible issues with crosslinks until #421 is merged, but this is sort of a pre-existing problem.
----
📚 Documentation preview 📚: https://pyttb--423.org.readthedocs.build/en/423/

Updates to tensor class documentation (only at module and class level)

---

pyttb/tensor.py

- Giving more explanation of input arguments.
- Removing statement about row vector because it shouldn't matter.
- Adding more pertinent examples, including constructing a tensor from a 3D numpy array and from a 1D numpy array.
- Moved the example of an empty constructor to be last (not sure it's even needed).
- Removed 2D conversion example.
_Note:_ This should not have any dependencies on other pull requests, excepting possible issues with crosslinks until #421 is merged. 
----
📚 Documentation preview 📚: https://pyttb--424.org.readthedocs.build/en/424/

Updating documentation for `pyttb.tensor.__init__`.

---

pyttb/tensor.py

Mainly making it very clear that it's a deep copy.
----
📚 Documentation preview 📚: https://pyttb--426.org.readthedocs.build/en/426/

Minor update to documentation of `pyttb.tensor.copy`. 

---

pyttb/tensor.py

- Added an example showing how to create a tensor with normal random entries, for which there is no current shortcut like `tenones`. 
- Used that example to show how it's arguably best to pass in a vector rather than trying to worry about forcing Fortran ordering.
- Also updated the example of create an all-ones tensor. The previous documentation relied on some function called `fortran_order_one`, and I'm not sure what that is. 
- Instead, I changed it to the `numpy.ones` function and to specify the fortran order via its interface. 
I think these examples will be helpful to users.
----
📚 Documentation preview 📚: https://pyttb--425.org.readthedocs.build/en/425/

Updating documentation of `pyttb.tensor.from_function`.

---

pyttb/tensor.py

- More documentation on the parameters.
- Showing that you can just pass in an ordinary sort of array to specify the collapse modes.
- More explanatory examples, also showing how to use a different collapse function.
----
📚 Documentation preview 📚: https://pyttb--427.org.readthedocs.build/en/427/

Updating documentation to `pyttb.tensor.collapse` function.

---

pyttb/cp_apr.py
pyttb/tucker_als.py

When checking for output, use divmod consistently across methods.
----
📚 Documentation preview 📚: https://pyttb--431.org.readthedocs.build/en/431/

430 replace divmod in checking for iteration output

---

pyttb/export_data.py
tests/test_import_export_data.py

Keeps fmt_data parameter for new tests for write/read efficiency.
----
📚 Documentation preview 📚: https://pyttb--449.org.readthedocs.build/en/449/

Adds index_base as argument to export_data.

---

tests/gcp/test_optimizers.py

Closes #451 
Reiterating some discussion on the ticket. Basically things were flaky because I used an adhoc method to generate bad steps to reject. If we just negate the function handle then as we approach the true solution we are approaching the maximum rather than the minimum. I ran this like 50 times and didn't get a flake.
----
📚 Documentation preview 📚: https://pyttb--452.org.readthedocs.build/en/452/

Make function handle opposite of true objective
